[package]
name = "ai_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
reqwest = { version = "0.12.8", features = ["rustls-tls", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
