[default.extend-words]

[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    ".gitignore",
    "**/notify_server/index.html",
    "**/node_modules/*",
    "**/fixtures/**",
    "assets/*",
    "chatapp/src/gen/*",
]
