@startjson data_structure
{
  "id": "chat_id",
  "ws_id": {
    "id": "workspace_id",
    "name": "workspace_name",
    "owner_id": "user_id",
    "created_at": "create timestamp"
  },
  "name": "chat_name",
  "type": ["single", "group", "private_channel", "public_channel"],
  "members": [{
    "id": "user_id",
    "ws_id": "workspace_id",
    "fullname": "user_fullname",
    "email": "user_email",
    "password_hash": "user_password_hash",
    "created_at": "create timestamp"
  }],
  "agents": [{
    "id": "agent_id",
    "chat_id": "chat_id",
    "name": "agent_name",
    "type": ["proxy", "relay", "tap"],
    "prompt": "agent_prompt",
    "adapter": ["openai", "ollama"],
    "model": ["gpt-4o", "llama3.2"],
    "args": "agent_args",
    "created_at": "create timestamp",
    "updated_at": "update timestamp"
  }],
  "created_at": "create timestamp"
}
@endjson