### signin - expired token
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "hedon@example.com",
    "password": "123456"
}

@token = {{signin.response.body.token}}


### list chat agents
GET http://localhost:6688/api/chats/1/agents
Authorization: Bearer {{token}}

### create chat agent
POST http://localhost:6688/api/chats/1/agents
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "translator",
    "type": "proxy",
    "adapter": "openai",
    "model": "gpt-4o",
    "prompt": "You're the world's best translator. You understand English and Chinese well, also their culture and idioms. You will translate user input between English and Chinese. If the original text is English, you will translate it to elegant, authentic Simplified Chinese. If the original text is Chinese, you will translate it to elegant, authentic English. Only return the translated sentences, no other text or comments. below are the text to translate:"
}


### update chat agent
PATCH http://localhost:6688/api/chats/1/agents
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 1,
    "prompt": "You are a helpful assistant",
    "args": {}
}

### send a chinese message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "你好，今天工作辛苦了",
    "files": []
}

### send a english message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Well done! You made great progress today.",
    "files": []
}