use crate::{AiAdapter, AiService, Message};

#[derive(Default)]
pub struct TestAdapter {}

impl AiService for TestAdapter {
    async fn complete(&self, _: &[Message]) -> anyhow::Result<String> {
        Ok("generated by test adapter".to_string())
    }
}

impl From<TestAdapter> for AiAdapter {
    fn from(value: TestAdapter) -> Self {
        AiAdapter::Test(value)
    }
}
